import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import vm from 'node:vm'
import { catalogTypes, planForMarket, quantityLabel } from '../src/utils/trip.js'
const source = readFileSync(new URL('../src/api/mockData.js', import.meta.url), 'utf8').replace(/^import (\w+) from .+$/gm, 'const $1 = "demo-image.jpg"').replaceAll('export ', '')
const seed = vm.runInNewContext(source + '\ncloneSeedData()')
assert.equal(seed.products.length, 40)
for (const product of seed.products) {
  const farmer = seed.farmers.find((item) => item.id === product.farmerId)
  assert(farmer)
  assert(product.marketIds.every((id) => farmer.marketIds.includes(id) && seed.markets.some((market) => market.id === id)))
  assert(product.image && product.unit && product.rating >= 0 && product.price > 0)
}
const types = catalogTypes(seed)
for (const category of ['Vegetables', 'Fruits', 'Dairy', 'Eggs', 'Bakery', 'Other Produce']) assert(types.some((type) => type.category === category))
const list = ['tomatoes:kg', 'spinach:bunch', 'eggs:dozen', 'bread:loaf'].map((key) => ({ ...types.find((type) => type.key === key), quantity: key === 'eggs:dozen' ? 1 : 2 }))
const plan = planForMarket(seed, seed.markets[0], list)
assert.equal(plan.foundCount, 4)
assert.equal(plan.total, 2000)
assert.equal(plan.stops.length, 3)
assert.equal(quantityLabel(list[2]), '12 eggs (1 dozen)')
const partial = planForMarket(seed, seed.markets[0], [...list, { ...types.find((type) => type.key === 'cheese:pack'), quantity: 1 }])
assert.equal(partial.foundCount, 4)
assert.equal(partial.total, plan.total)
const overstock = planForMarket(seed, seed.markets[0], [{ ...list[0], quantity: 999 }])
assert.equal(overstock.foundCount, 0)
assert.equal(overstock.total, 0)
const storage = new Map()
const old = structuredClone(seed)
old.products = old.products.filter((product) => Number(product.id.slice(2)) < 30)
old.products[0].stock = 4
storage.set('marketlink_demo_db_v1', JSON.stringify(old))
const apiSource = readFileSync(new URL('../src/api/index.js', import.meta.url), 'utf8').replace(/^import .+$/gm, '').replace("import.meta.env.VITE_API_URL?.replace(/\\/$/, '')", 'undefined').replace('export const api', 'const api').replace('export default api', '')
const api = vm.runInNewContext(apiSource + '\napi', { cloneSeedData: () => structuredClone(seed), uid: () => 'test-' + Math.random(), localStorage: { getItem: (key) => storage.get(key), setItem: (key, value) => storage.set(key, value) }, window: { dispatchEvent() {} }, CustomEvent: class {}, setTimeout })
const migrated = api.snapshot()
assert.equal(migrated.products.length, 40)
assert.equal(migrated.products[0].stock, 4)
assert.equal(migrated.orders.length, old.orders.length)
const orders = await api.orders.createBatch({ customerId: 'u-customer', marketId: plan.market.id, pickupDate: '26 Sep 2026', pickupSlot: '10:00–10:30 AM', items: plan.picks.map((pick) => ({ productId: pick.product.id, quantity: pick.quantity })) })
assert.equal(orders.length, 3)
assert.equal(orders.reduce((sum, order) => sum + order.total, 0), plan.total)
for (const pick of plan.picks) assert.equal(api.snapshot().products.find((product) => product.id === pick.product.id).stock, pick.product.stock - pick.quantity)
await assert.rejects(() => api.orders.createBatch({ customerId: 'u-customer', marketId: 'm-1', pickupDate: '26 Sep 2026', pickupSlot: '10:00 AM', items: [{ productId: 'p-33', quantity: 1 }] }), /cannot be collected/)
console.log('PASS: catalog relationships, category coverage, quantities, totals, partial availability, stock limits, migration preservation, reservation grouping and stock updates')


// Dashboard persistence and session contracts, using an isolated demo store.
const newMarket = api.markets.save({ name: 'Test Weekend Market', address: 'Demo Lahore', day: 'Saturday', openingTime: '08:00', closingTime: '13:00', lat: 31.5, lng: 74.3 })
assert(api.snapshot().markets.some((market) => market.id === newMarket.id))
api.markets.save({ ...newMarket, name: 'Updated Weekend Market', openingTime: '09:00', closingTime: '14:00' })
assert.equal(api.snapshot().markets.find((market) => market.id === newMarket.id).hours, '09:00 - 14:00')
assert.throws(() => api.markets.save({ ...newMarket, lat: 100 }), /valid coordinates/)
assert.throws(() => api.markets.remove('m-1'), /active pickups/)
api.markets.remove(newMarket.id)
assert(!api.snapshot().markets.some((market) => market.id === newMarket.id))
const order = orders[0]
await api.orders.updateStatus(order.id, 'accepted')
await api.orders.updateStatus(order.id, 'preparing')
await api.orders.updateStatus(order.id, 'ready')
await api.orders.updateStatus(order.id, 'completed')
const review = await api.reviews.create({ orderId: order.id, productId: order.items[0].productId, customerId: 'u-customer', customer: 'Demo Customer', rating: 5, comment: 'Fresh and easy to collect.' })
assert(api.snapshot().reviews.some((item) => item.id === review.id))
api.reviews.respond(review.id, order.farmerId, 'Thank you for visiting.')
assert.equal(api.snapshot().reviews.find((item) => item.id === review.id).response, 'Thank you for visiting.')
await assert.rejects(() => api.reviews.create({ orderId: order.id, productId: order.items[0].productId, customerId: 'u-customer', rating: 5, comment: 'Duplicate' }), /already reviewed/)
await api.users.toggleFavorite('u-customer', 'f-3')
assert(api.snapshot().users.find((user) => user.id === 'u-customer').favorites.includes('f-3'))
const authSource = readFileSync(new URL('../src/context/AuthContext.jsx', import.meta.url), 'utf8')
const logoutBody = authSource.match(/const logout = \(\) => \{([\s\S]*?)\n  \}/)[1]
for (const role of ['customer', 'farmer', 'admin']) {
  storage.set('marketlink_session', JSON.stringify({ user: { role } }))
  storage.set('marketlink_token', 'demo-' + role)
  storage.set('marketlink_cart', 'preserved-basket')
  let currentUser = { role }; let destination = null
  vm.runInNewContext(logoutBody, { SESSION_KEY: 'marketlink_session', localStorage: { removeItem: (key) => storage.delete(key) }, setUser: (value) => { currentUser = value }, navigate: (path) => { destination = path } })
  assert.equal(currentUser, null); assert.equal(destination, '/')
  assert(!storage.has('marketlink_session')); assert(!storage.has('marketlink_token'))
  assert.equal(storage.get('marketlink_cart'), 'preserved-basket')
  const dashboard = readFileSync(new URL('../src/pages/' + role + '/' + role[0].toUpperCase() + role.slice(1) + 'Dashboard.jsx', import.meta.url), 'utf8')
  assert(dashboard.includes('onClick={logout}'))
}
console.log('PASS: market CRUD and validation, active-pickup deletion protection, preparing lifecycle, reviews/replies, favorites, shared logout for all 3 roles and basket preservation')

const acceptedNotice = api.snapshot().notifications.find((item) => item.orderId === order.id && item.type === 'accepted')
const readyNotice = api.snapshot().notifications.find((item) => item.orderId === order.id && item.type === 'ready')
assert(acceptedNotice && readyNotice)
assert(api.snapshot().notifications.some((item) => item.orderId === order.id && item.type === 'reminder'))
await api.notifications.markRead(acceptedNotice.id)
assert.equal(api.snapshot().notifications.find((item) => item.id === acceptedNotice.id).unread, false)
api.subscriptions.notifyMe('u-customer', 'p-6')
api.subscriptions.notifyMe('u-customer', 'p-6')
assert.equal(api.snapshot().stockSubscriptions.filter((item) => item.productId === 'p-6').length, 1)
await api.products.update('p-6', { stock: 10, available: true })
assert.equal(api.snapshot().notifications.filter((item) => item.productId === 'p-6' && item.type === 'restock').length, 1)
await api.products.update('p-6', { stock: 12, available: true })
assert.equal(api.snapshot().notifications.filter((item) => item.productId === 'p-6' && item.type === 'restock').length, 1)
api.announcements.publish('Saturday pickup reminder')
assert(api.snapshot().notifications.some((item) => item.type === 'announcement' && item.userId === 'u-customer'))
await api.notifications.markAllRead('u-customer')
assert(api.snapshot().notifications.filter((item) => item.userId === 'u-customer').every((item) => !item.unread))
const { pickupDates } = await import('../src/utils/pickup.js')
assert.deepEqual(pickupDates({ day: 'Saturday' }, new Date(2026, 8, 25)), ['26 Sept 2026', '03 Oct 2026', '10 Oct 2026', '17 Oct 2026'])
assert.equal(pickupDates({ day: 'No operating days' }).length, 0)
const { getAvailability, getFreshness } = await import('../src/utils/helpers.js')
assert.deepEqual([getAvailability({ available: true, stock: 20 }), getAvailability({ available: true, stock: 8 }), getAvailability({ available: true, stock: 2 }), getAvailability({ available: false, stock: 0 }), getAvailability({ available: true, stock: 12, recentlyRestocked: true })].map((item) => item.label), ['In Stock', 'Limited Stock', 'Almost Sold Out', 'Sold Out', 'Recently Restocked'])
assert.equal(getFreshness({ category: 'Dairy', harvestDaysAgo: 0 }).harvestLabel, '')
console.log('PASS: accepted/ready/reminder/restock/announcement notifications, subscriptions, mark read/all, pickup dates and all five availability states')
