import { ArrowRight, Clock3, MapPin, Navigation } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import api from '../../api'

export default function MarketsPage() {
  const db = api.snapshot()
  const [active, setActive] = useState(db.markets[0])
  const [view, setView] = useState('list')
  return <main><section className="page-hero page-hero--map"><div className="shell"><p className="eyebrow eyebrow--gold">PICKUP POINTS</p><h1>Your local market, <em>mapped.</em></h1><p>Plan one good trip: see opening times, active growers and exact pickup points.</p></div></section><div className="shell filter-pills market-view-switch"><button className={view === 'list' ? 'is-active' : ''} onClick={() => setView('list')}>List View</button><button className={view === 'map' ? 'is-active' : ''} onClick={() => setView('map')}>Map View</button></div><section className={`markets-browser shell markets-browser--${view}`}><div className="market-browser-list"><div className="browser-head"><div><span>{db.markets.length} MARKETS NEARBY</span><h2>This week in Lahore</h2></div></div>{db.markets.map((market) => <button key={market.id} onClick={() => { setActive(market); setView('map') }} className={`market-browser-card ${active.id === market.id ? 'is-active' : ''}`}><span className="market-date"><b>{market.date.split(' ')[0]}</b>{market.date.split(' ')[1]}</span><div><h3>{market.name}</h3><p><Clock3 /> {market.day} · {market.hours}</p><p><MapPin /> {market.address}</p><small>{market.stalls} stalls · {market.distance} away</small></div><ArrowRight /></button>)}</div>{view === 'map' && active && <div className="live-map"><iframe title="OpenStreetMap market location" src={`https://www.openstreetmap.org/export/embed.html?bbox=${active.lng - 0.03}%2C${active.lat - 0.02}%2C${active.lng + 0.03}%2C${active.lat + 0.02}&layer=mapnik&marker=${active.lat}%2C${active.lng}`} loading="lazy" /><div className="map-card"><span><MapPin /></span><div><small>SELECTED PICKUP POINT</small><strong>{active.name}</strong><p>{active.address}</p></div><a className="icon-btn" aria-label="Directions to selected market" href={`https://www.openstreetmap.org/directions?to=${active.lat},${active.lng}`} target="_blank" rel="noreferrer"><Navigation /></a></div></div>}</section><section className="section section--paper"><div className="shell"><div className="center-heading"><p className="eyebrow">PLAN AHEAD</p><h2>One trip. <em>A full basket.</em></h2><p>Reserve from participating farmers and collect everything in your chosen window.</p></div><div className="simple-card-grid">{db.markets.map((market) => <article key={market.id}><span>{market.day.slice(0, 3)}</span><h3>{market.name}</h3><p>{market.description}</p><p>{market.day} ? {market.hours}</p><p>{market.address}</p><a className="arrow-link" href={`https://www.openstreetmap.org/directions?to=${market.lat},${market.lng}`} target="_blank" rel="noreferrer">View Map / Directions <Navigation /></a><Link className="arrow-link" to={`/markets/${market.id}`}>View market <ArrowRight /></Link></article>)}</div></div></section></main>
}
